name: CI

on:
  push:
    branches: "**"
    pull_request:

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            swift: "5.9"
          - os: ubuntu-latest
            swift: "5.9"

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
        if: matrix.os != 'ubuntu-latest'

      - uses: actions/checkout@v3

      - name: "swift test"
        run: swift test

      - name: build
        run: swift build -c release

      - name: "test: version"
        run: $(swift build -c release --show-bin-path)/spx --version

      - name: "test: help"
        run: $(swift build -c release --show-bin-path)/spx --help

      - name: "test: init"
        run: $(swift build -c release --show-bin-path)/spx --init simple

      - name: "test: add"
        run: $(swift build -c release --show-bin-path)/spx --add date2

      - uses: actions/upload-artifact@v3
        with:
          name: spx-init-${{ matrix.swift }}-${{ matrix.os }}
          path: SPX

      - name: "test: run"
        run: $(swift build -c release --show-bin-path)/spx date2

      - name: "test: build"
        run: $(swift build -c release --show-bin-path)/spx --build

      - name: "reset spx dir"
        run: rm -fr SPX

      - name: "template ios - scaffold"
        run: $(swift build -c release --show-bin-path)/spx -i ios

      - name: "template ios - build"
        run: $(swift build -c release --show-bin-path)/spx --build
        if: ${{ matrix.os == 'macos-13' }}

      - name: "template ios - generate app icon"
        run: $(swift build -c release --show-bin-path)/spx appicon
        if: ${{ matrix.os == 'macos-13' }}

      - uses: actions/upload-artifact@v3
        with:
          name: spx-ios-${{ matrix.swift }}-${{ matrix.os }}
          path: |
            SPX
            !.build

      - name: "demo: build container"
        run: cd demos/VaporDemo && $(swift build -c release --package-path ../.. --show-bin-path)/spx docker
        if: ${{ matrix.os != 'macos-13' }}

      - name: "demo: update and test"
        run: cd demos/VaporDemo && $(swift build -c release --package-path ../.. --show-bin-path)/spx UpdateAndTest
